### ISSUE TITLE
`mad_tpsa_liebra` sign error?

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#426]
Maybe this is just a matter of convention, but I noticed that mad_tpsa_liebra gives an opposite sign of what is in Etienne's blue book equation 3.39. For example if I replicate the example in the blue book Eqs 3.45-3.47, I get -H for eq 3.47

**Comment by ldeniau** [comment]
Do you have a simple example? Just to be sure that we do the same thing...

However, it seems that is not a convention but a bug (!) that strangely does not affect the logpb, i.e. eq. 11.8 in Etienne's blue book, and logpb is used in RDTs analysis to extract Hamiltonian terms and generating functions...
Fixed in b6446f2c
