### ISSUE TITLE
Overconstraint in `compose`

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#446]
https://github.com/MethodicalAcceleratorDesign/MAD-NG/blob/2f03064bc6855e06469574e55e71c8a73c1892c1/src/mad_tpsa_comp.c#L47

Say I have two variables and some function $f: \mathbb{R}^2\rightarrow\mathbb{R}^4$ , and another function $g:  \mathbb{R}^2\rightarrow\mathbb{R}^2$ . With this constraint I cannot compute $f\circ g$. In the linear case this is equivalent to not allowing the product of a $4\times 2$ matrix with a $2 \times 2$ matrix e.g. $A_{4\times 2} B_{2\times 2}$.

**Comment by ldeniau** [comment]
I don't see any correct damap function that would extend the damap dimension through composition.  $f\circ g$ means that each monomial of the functions of $f$ (variables only) are substituted by the functions of $g$ (i.e. variables and parameters) where $f$ and $g$ must have the same structure. Thus [4x2] x [2x2] is an invalid operation for damap, while [2x4] x [4x4] is valid one.

**Comment by mattsignorelli** [comment]
Basically I am saying that with $f: \mathbb{R}^2\rightarrow\mathbb{R}^4$ and $g:  \mathbb{R}^2\rightarrow\mathbb{R}^2$, then $f\circ g$ is a perfectly valid operation. Of course each component of $f$ no longer "corresponds" to a variable in the Descriptor, but it still should be allowed. The current workaround that I could do here is to just call `compose` with each component of $f$, e.g. $f_i \circ g$ for i = {1,2,3,4}, but this shouldn't be necessary. A quick look at the code seems like removing this line I quote in my first comment is safe.

When I call `compose`, I just feed it a vector of tpsas, I am not using any "damap" type implemented in MAD-NG. I am using `mad_tpsa_compose` or `mad_ctpsa_compose`.

As I mentioned over email, the immediate application of this is a quaternion. The quaternion implementation certainly should not be handled by the TPSA package, or implemented in the tpsa package. It should be done at the higher level. In Julia, I already have a quaternion type implemented which can consist of either regular numbers, or tpsa's, or whatever numbers someone wants to use in there. The multiplication rules for each component $q_0, q_1, q_2, q_3$ in the quaternion are the same regardless

Say I have some orbital map $\vec{M}:\mathbb{R}^{NV}\rightarrow\mathbb{R}^{NV}$, then I need to compute the quaternion

$$ \mathbf{q}(\vec{M}(\vec{z}_0)) = \mathbf{q}\circ\vec{M}$$

Which for 1D orbit motion `NV=2` we have $\mathbf{q}(x,p_x) = [q_0(x,p_x), q_1(x,p_x), q_2(x,p_x),q_3(x,p_x)]$ which is exactly the $f\circ g$ that I described above, presuming I've stored $\mathbf{q}$ internally as just a vector of 4 tpsas and also $\vec{M}$ as just a vector of NV tpsas internally.

**Comment by ldeniau** [comment]
We'll be discussing this live soon, but the statement "A quick look at the code seems like removing this line I quote in my first comment is safe." is wrong.  Extending `sa` beyond `nv` means that parameter functions will be composed too and this is not allowed, only variable functions can be composed on the left side of the operator. The only thing that can be changed in parameters is their scalar value, otherwise, it's not parameters.

**Comment by ldeniau** [comment]
Following our discussion, I have looked at the code and don't think using `compose` on each quaternion component separately would be slower than using `compose` on the four components simultaneously. Nevertheless, I extended the `compose` function to skip this test if `sa < 0`. So just provide `-sa` to `compose` an array of TPSA not representing a damap, e.g. quaternion components.

**Comment by ldeniau** [comment]
To conclude this discussion, the algebra of the quaternion should not be mixed with the algebra of the TPSA, one must enclose the other, i.e. $T[\mathbb{H}]$ (like $T[\mathbb{C}]$) or $Q[\mathbb{T}]$ like in Matt's request. Nevertheless, the `compose` function has been extended to allow the simultaneous composition of a set of TPSA with a DA map (right operand). It must only be seen as a speed optimization, not an extension of the algebra, to perform one composition of N TPSAs instead of N compositions of one TPSA, both with a DA map.
